### ISSUE TITLE
Question about the lowering of `i1`.

### ISSUE THREAD

**Issue by miloudi98** [Sirraide/source-mlir#2]
https://github.com/Sirraide/source/blob/8c8399bef054c983187f91b8cd1fdcdbcc68fd46/tests/cast.src#L50

Sorry if this is not a good way of asking questions about your project.

Do `i1`s get treated specially when lowering or in codegen or are they simply `u8`s underneath?
More specifically, does a `vector<i1>` have the **same** memory layout as a `vector<u8>`?

Also, what's the benefit from creating the distinction between `bool` and `i1`. I read the comment about what the difference is, but I don't think I saw one explaining why we need the distinction in the first place (Sorry if I missed it).

I'm looking to implement a compiler soon, that's why I am a interested in the project.

**Comment by Sirraide** [comment]
> Do `i1`s get treated specially when lowering or in codegen or are they simply `u8`s underneath? More specifically, does a `vector<i1>` have the **same** memory layout as a `vector<u8>`?

An `i1` is not the same as an `i8` in that the former is 1 bit, the latter 8; e.g. adding two `i1`s that both have the value `1` will wrap and yield `0`, whereas for `i8`s, it yields `2`. However, CPUs typically don’t support addressing single bits, so an `i1` will still have 1-byte *alignment*, which means that, yes, an array of `i1` will occupy the same amount of space as an array of `i8`. One exception to this would be in a packed struct where all the fields are squished together w/ no regard for alignment, in which case 8 `i1`s in a row would only occupy 1 byte (however, in that case, you also would not be able to e.g. take the address of any of those `i1`s since a ‘pointer’ to a single bit is not representable). The same also applies to LLVM’s vector types (think SIMD vectors, not dynamic-array vectors).


> Also, what's the benefit from creating the distinction between `bool` and `i1`. I read the comment about what the difference is, but I don't think I saw one explaining why we need the distinction in the first place (Sorry if I missed it).
 
`bool` is special in that `0` is `false`, but *any other value* is `true`. That means that e.g. `4 as bool` yields true as `4` is truthy, but an `i1` is just a regular integer type, so `4 as i1` yields `0`, as `4` is `0b100`, which is simply truncated by chopping off all but the last bit, which, in this case, ends up being `0`. As to why we *need* to differentiate between the two... we don’t, really, but `bool` is logically a distinct type at the language level, and I see no harm in providing this distinction in case it’s ever needed. I don’t expect `i1`s to be used too widely. (Also, in the IR, both are represented by the `i1` type).

**Comment by miloudi98** [comment]
I see now... I appreciate the detailed explanation.
Closing the issue.
